# Generated by Django 4.1.6 on 2023-02-16 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=100)),
                ('breed_origin', models.CharField(max_length=100)),
                ('breed_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=200)),
                ('home_address', models.CharField(max_length=300)),
                ('house_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(max_length=200)),
                ('human_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('human_date_of_birth', models.DateField(verbose_name='date of birth')),
                ('human_description', models.CharField(max_length=300)),
                ('human_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catwiki.home')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cat_date_of_birth', models.DateField(verbose_name='date of birth')),
                ('cat_description', models.CharField(max_length=300)),
                ('cat_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catwiki.breed')),
                ('cat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catwiki.human')),
            ],
        ),
    ]
