# Generated by Django 4.1.6 on 2023-02-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='human',
            name='human_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
