# Generated by Django 4.1.6 on 2023-02-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0004_alter_cat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='slug',
        ),
    ]
