# Generated by Django 4.1.6 on 2023-02-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0005_remove_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='catwiki.breed'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='catwiki.human'),
        ),
        migrations.AlterField(
            model_name='human',
            name='human_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='catwiki.home'),
        ),
    ]
