# Generated by Django 4.1.6 on 2023-02-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0006_alter_cat_cat_breed_alter_cat_cat_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='catwiki.breed'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedby', to='catwiki.human'),
        ),
    ]
