# Generated by Django 4.1.6 on 2023-02-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0008_alter_cat_cat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='house_type',
            field=models.CharField(choices=[('Landed', 'landed'), ('Condominium', 'condominium')], max_length=50),
        ),
    ]
