# Generated by Django 4.1.6 on 2023-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0009_alter_home_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='house_type',
            field=models.CharField(choices=[('landed', 'Landed'), ('condominium', 'Condominium')], max_length=50),
        ),
    ]
