# Generated by Django 4.1.6 on 2023-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0010_alter_home_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
